variables:
  Project name: scala-project-template
  Organization: org.organization
features:
- scala:
    description: Basic template to kickstart Scala projects
- ci.circle:
    description: Build on Circle CI
conflicts:
- ci.travis
