variables:
  Project name: scala-project-template
  Organization: org.organization
features:
- scala:
    description: Basic template to kickstart Scala projects
- ci.travis:
    description: Build on Travis CI
conflicts:
- ci.circle
excludes:
- /.github
