variables:
  Project name: scala-project-template
  Organization: org.organization
features:
  - FEATURE-circle.ci:
      description: Basic template to kickstart Scala projects 2
excludes:
  - /.github
