name: Propagate template changes

on: [push]

jobs:
  propagate:
    name: Propagate template changes
    if: github.repository == 'rtimush/scala-project-template'
    runs-on: ubuntu-latest
    steps:
    - uses: tenpureto/propagate-changes-action@v1
      with:
        pull-request-label: pr:propagating-changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
